import Head from 'next/head'
import { Inter } from 'next/font/google'
import Home from './home/index.jsx'
import Header from '@/components/layout/Header.jsx'
import Karussell from '@/components/ui/Karussell.jsx'
import Footer from '@/components/layout/Footer.jsx'
import axios from 'axios'

export default function Index({categoryList}) {
  return (
    <div className='relativ'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        

      </Head>
      
      <Home categoryList={categoryList}/>
    </div>
  )
}

export const getServerSideProps=async () =>{
  const res =await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/categories`)
  return {
    props :{
      categoryList :res.data ? res.data:[]
    }
  }
}